version: "3"

services:
  web:
    build: .
    links:
      - "db:postgres"
    ports:
      - "8000:80"
    volumes:
      - "./data:/data:rw"
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./data/db:/var/lib/postgresql/data:rw"
      - ".:/var/www/html:rw"
