version: "2.3"

services:
  web:
    build: .
    links:
      - "db:postgres"
    ports:
      - "8000:80"
    volumes:
      - ".:/var/www/html:rw"
      - "./data:/data:rw"
      - "./modules:/var/www/html/modules:rw"
      - "./profiles:/var/www/html/profiles:rw"
      - "./themes:/var/www/html/themes:rw"
      - "./sites:/var/www/html/sites:rw"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/db

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./data/db:/var/lib/postgresql/data:rw"
      - ".:/var/www/html:rw"

volumes:
    modules:
    profiles:
    themes:
    sites: